### ISSUE TITLE
[SUGGESTION] Use Essentials#getVanishedPlayers() in ExprVanishedPlayers

### ISSUE THREAD

**Issue by cheeezburga** [EquipableMC/SkEssentials#3]
I think you can just use [this](https://github.com/EssentialsX/Essentials/blob/f1a5caf98eada55901602a66cb3f92be818f3d91/Essentials/src/main/java/com/earth2me/essentials/Essentials.java#L1353) method instead of looping through the players.

**Comment by EquipableMC** [comment]
Done! #4
